Improvement, shoot, worker group node max / min count
gardener/gardener-metrics-exporter pull request #95
Opened 2023-12-29 16:29 UTC by Sinscerly

Feature add worker node max / min count (and worker type as label)

**What this PR does / why we need it**:
- This PR adds two extra metrics: `garden_shoot_worker_node_max_total` and `garden_shoot_worker_node_min_total`. This gives insight about the min and max worker nodes for a shoot.

**Which issue(s) this PR fixes**:
Fixes  #45

**Special notes for your reviewer**:
Adding `garden_shoot_worker_node_max_total` and `garden_shoot_worker_node_min_total` can remove the current `garden_shoot_node_max_total` and `garden_shoot_node_min_total`. As the worker nodes counts can be summed for the total shoot.

**Release note**:
```
Adds: garden_shoot_worker_node_max_total and garden_shoot_worker_node_min_total. Also gives insight into the worker type (for example for OpenStack the Flavor name).
```

2024-02-05 16:09 UTC, rickardsjp requested changes
Thank you @Sinscerly for your contribution. Only a small nitpick.

2024-02-07 10:24 UTC, rickardsjp commented
/lgtm

2024-02-07 10:25 UTC, rickardsjp approved these changes
/lgtm

2024-02-07 10:25 UTC, Sinscerly commented on README.md
> +| garden_shoot_worker_node_max_total      | Max worker node count of a Shoot worker group                                    | Shoot    | Gauge   |
@rickardsjp thank you for pointing out. I've changed it to match the other descriptions:

```markdown
| garden_shoot_node_min_total             | Min node count of a Shoot                                                 | Shoot    | Gauge   |
| garden_shoot_node_max_total             | Max node count of a Shoot                                                 | Shoot    | Gauge   |
| garden_shoot_worker_node_min_total      | Min node count of a Shoot worker group                                    | Shoot    | Gauge   |
| garden_shoot_worker_node_max_total      | Max node count of a Shoot worker group                                    | Shoot    | Gauge   |
```
Let me know if this is what you meant.

2024-02-07 10:26 UTC, rickardsjp commented on README.md
> +| garden_shoot_worker_node_max_total      | Max worker node count of a Shoot worker group                                    | Shoot    | Gauge   |
That's what I was referring to, thanks for taking care of it.

2024-02-07 10:39 UTC, merged